configuración levantamiento de minikube

diff --git a/JenkinsfileInfra b/JenkinsfileInfra
--- a/JenkinsfileInfra
+++ b/JenkinsfileInfra
@@ -102,7 +102,16 @@ pipeline {
                     // Conectar por SSH a la instancia EC2 para validar o configurar más cosas si es necesario
                     sh """
                     ssh -o StrictHostKeyChecking=no -i ${SSH_PRIVATE_KEY} ec2-user@${instance_ip} << EOF
-                    # (Aquí puedes agregar más comandos o scripts si es necesario)
+                    sudo minikube start --driver=none
+                    if [ -f /root/.kube/config ]; then
+                        sudo mkdir -p /home/ec2-user/.kube /home/ec2-user/.minikube
+                        sudo cp -r /root/.kube/* /home/ec2-user/.kube/
+                        sudo cp -r /root/.minikube/* /home/ec2-user/.minikube/
+                        sudo chown -R ec2-user:ec2-user /home/ec2-user/.kube /home/ec2-user/.minikube
+                    else
+                        echo "Minikube configuration not found."
+                        exit 1
+                    fi
                     kubectl get nodes
                     EOF
                     """
